### PR TITLE
Complete rework for python3-ovirt-engine-sdk4 API

### PR DESCRIPTION
**Pull request by valeriop**
Tested with CentOS 8, oVirtEngine 4.4 and python3-ovirt-engine-sdk4-4.4.4-1.el8

### CODE REVIEW

**Comment by ekim78** [comment]
Tell me please, how to solve this:

Traceback (most recent call last):
  File "/usr/local/sbin/ovirt-vm-backup/backup.py", line 464, in <module>
    main(sys.argv[1:])
  File "/usr/local/sbin/ovirt-vm-backup/backup.py", line 228, in main
    if system_service.storage_domains_service().list(search='name=%s' % config.get_export_domain() )[0] is None:
IndexError: list index out of range

**Comment by valeriop** [comment]
Hi
Please check in your system the Export Storage name and modify it in your configuration (.cfg) file:

# Name of the NFS Export Domain
export_domain=backup
 
Regards

Il 28 dicembre 2020 20:03:38 CET, ekim78 <notifications@github.com> ha scritto:

**Comment by ekim78** [comment]
Hi
Many thanks for clarification. I'm sorry for being inattentive. I corrected the config file and everything worked.

**Review by wefixit-AT — APPROVED** [review]

**Comment by wefixit-AT** [comment]
Thank you

**Comment by wefixit-AT** [comment]
Thank you

**Pull request merged**
